/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Application {
  constructor(options?: ApplicationOptions | undefined | null)
  onEvent(handler?: ((arg: ApplicationEvent) => void) | undefined | null): void
  bind(handler?: ((arg: ApplicationEvent) => void) | undefined | null): void
  exit(): void
  createBrowserWindow(options?: BrowserWindowOptions | undefined | null): BrowserWindow
  createChildBrowserWindow(options?: BrowserWindowOptions | undefined | null): BrowserWindow
  setMenu(menuOptions?: MenuOptions | undefined | null): void
  /**
   * Pump the winit event loop once without blocking. Returns `true` while
   * the app is alive, `false` when it should stop. Drive this from a JS
   * `setInterval` via the `run()` wrapper in `index.js`.
   */
  pumpEvents(): boolean
  /** Run the application event loop. */
  run(options?: ApplicationRunOptions | undefined | null): void
}

export declare class BrowserWindow {
  createWebview(options?: WebviewOptions | undefined | null): JsWebview
  get isChild(): boolean
  isFocused(): boolean
  isVisible(): boolean
  isDecorated(): boolean
  isClosable(): boolean
  isMaximizable(): boolean
  isMinimizable(): boolean
  isMaximized(): boolean
  isMinimized(): boolean
  isResizable(): boolean
  setTitle(title: string): void
  get title(): string
  setClosable(closable: boolean): void
  setMaximizable(maximizable: boolean): void
  setMinimizable(minimizable: boolean): void
  setResizable(resizable: boolean): void
  setSize(width: number, height: number): void
  openFileDialog(options?: FileDialogOptions | undefined | null): Array<string>
  id(): number
  hasMenu(): boolean
  get theme(): Theme
  setTheme(theme: Theme): void
  setWindowIcon(icon: Array<number> | string, width: number, height: number): void
  removeWindowIcon(): void
  setVisible(visible: boolean): void
  /** No-op: winit does not expose a progress bar API. */
  setProgressBar(state: JsProgressBar): void
  setMaximized(value: boolean): void
  setMinimized(value: boolean): void
  focus(): void
  getAvailableMonitors(): Array<Monitor>
  getCurrentMonitor(): Monitor | null
  getPrimaryMonitor(): Monitor | null
  /** Not available in winit; always returns `None`. */
  getMonitorFromPoint(x: number, y: number): Monitor | null
  setContentProtection(enabled: boolean): void
  setAlwaysOnTop(enabled: boolean): void
  setAlwaysOnBottom(enabled: boolean): void
  setDecorations(enabled: boolean): void
  get fullscreen(): FullscreenType | null
  setFullscreen(fullscreenType?: FullscreenType | undefined | null): void
  close(): void
  hide(): void
  show(): void
}

export declare class Webview {
  constructor()
  onIpcMessage(handler?: ((arg: IpcMessage) => void) | undefined | null): void
  print(): void
  zoom(scaleFactor: number): void
  setWebviewVisibility(visible: boolean): void
  isDevtoolsOpen(): boolean
  openDevtools(): void
  closeDevtools(): void
  loadUrl(url: string): void
  loadHtml(html: string): void
  evaluateScript(js: string): void
  evaluateScriptWithCallback(js: string, callback: ((err: Error | null, arg: string) => any)): void
  reload(): void
}
export type JsWebview = Webview

export interface ApplicationEvent {
  event: WebviewApplicationEvent
  customMenuEvent?: CustomMenuEvent
}

export interface ApplicationOptions {
  controlFlow?: ControlFlow
  waitTime?: number
  exitCode?: number
}

export interface ApplicationRunOptions {
  /** The interval in milliseconds to pump events. Defaults to 16 (60 FPS).  */
  interval?: number
  /** Whether to keep the event loop alive. Defaults to true.  */
  ref?: boolean
}

export interface BrowserWindowOptions {
  menu?: MenuOptions
  showMenu?: boolean
  resizable?: boolean
  title?: string
  width?: number
  height?: number
  x?: number
  y?: number
  contentProtection?: boolean
  alwaysOnTop?: boolean
  alwaysOnBottom?: boolean
  visible?: boolean
  decorations?: boolean
  visibleOnAllWorkspaces?: boolean
  maximized?: boolean
  maximizable?: boolean
  minimizable?: boolean
  focused?: boolean
  transparent?: boolean
  fullscreen?: FullscreenType
}

/** Kept for backward compat; no longer used internally. */
export declare enum ControlFlow {
  Poll = 0,
  Wait = 1,
  WaitUntil = 2,
  Exit = 3,
  ExitWithCode = 4
}

export interface CustomMenuEvent {
  id: string
  windowId: number
}

export interface Dimensions {
  width: number
  height: number
}

export interface FileDialogOptions {
  multiple?: boolean
  title?: string
  defaultPath?: string
  filters?: Array<FileFilter>
}

export interface FileFilter {
  name: string
  extensions: Array<string>
}

export declare enum FullscreenType {
  Exclusive = 0,
  Borderless = 1
}

export declare function getWebviewVersion(): string

export interface HeaderData {
  key: string
  value?: string
}

export declare function initMenuSystem(): void

export interface IpcMessage {
  body: Buffer
  method: string
  headers: Array<HeaderData>
  uri: string
}

export interface JsProgressBar {
  state?: ProgressBarState
  progress?: number
}

export interface MenuItemOptions {
  id?: string
  label?: string
  enabled?: boolean
  accelerator?: string
  submenu?: MenuOptions
  role?: string
}

export interface MenuOptions {
  items: Array<MenuItemOptions>
}

export interface Monitor {
  name?: string
  scaleFactor: number
  size: Dimensions
  position: Position
  videoModes: Array<VideoMode>
}

export interface Position {
  x: number
  y: number
}

export declare enum ProgressBarState {
  None = 0,
  Normal = 1,
  Indeterminate = 2,
  Paused = 3,
  Error = 4
}

export declare enum Theme {
  Light = 0,
  Dark = 1,
  System = 2
}

export interface VideoMode {
  size: Dimensions
  bitDepth: number
  refreshRate: number
}

export declare enum WebviewApplicationEvent {
  WindowCloseRequested = 0,
  ApplicationCloseRequested = 1,
  CustomMenuClick = 2
}

export interface WebviewOptions {
  url?: string
  html?: string
  width?: number
  height?: number
  x?: number
  y?: number
  enableDevtools?: boolean
  incognito?: boolean
  userAgent?: string
  child?: boolean
  preload?: string
  transparent?: boolean
  theme?: Theme
  hotkeysZoom?: boolean
  clipboard?: boolean
  autoplay?: boolean
  backForwardNavigationGestures?: boolean
}

export declare enum WindowCommand {
  Close = 0,
  Show = 1,
  Hide = 2
}
